# Generated by Django 5.0.3 on 2024-05-15 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_wishlist_wishlistitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='referrel_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
