# Generated by Django 5.0.3 on 2024-05-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='yellow', max_length=100),
            preserve_default=False,
        ),
    ]
