# Generated by Django 5.0.3 on 2024-04-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Total_price',
            new_name='total_price',
        ),
    ]
