# Generated by Django 5.0.3 on 2024-05-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_orderitem_status_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_cancelled',
        ),
        migrations.AddField(
            model_name='order',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
